# Generated by Django 4.2.1 on 2023-05-20 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disease', '0009_delete_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('age', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bad_habit_groups', models.ManyToManyField(to='disease.badhabitsgroup')),
                ('bad_habits', models.ManyToManyField(to='disease.badhabits')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('symptom_groups', models.ManyToManyField(to='disease.symptomsgroup')),
                ('symptoms', models.ManyToManyField(to='disease.symptoms')),
            ],
        ),
    ]
