# Generated by Django 4.2.1 on 2023-05-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(max_length=100, unique=True)),
                ('english_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='bad_habits',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='symptoms',
        ),
    ]
