# Generated by Django 4.2.1 on 2023-05-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_check', '0002_unknownsymptoms_remove_searchhistory_bad_habits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(max_length=100, unique=True)),
                ('english_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
