# Generated by Django 4.2.1 on 2023-05-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_alter_diseasehistory_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.ManyToManyField(to='disease.symptoms')),
            ],
        ),
        migrations.CreateModel(
            name='BadHabitsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bad_habits', models.ManyToManyField(to='disease.badhabits')),
            ],
        ),
    ]
