# Generated by Django 4.2.1 on 2023-05-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_symptomsgroup_badhabitsgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='badhabitsgroup',
            name='chinese_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='symptomsgroup',
            name='chinese_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
