# Generated by Django 4.2.1 on 2023-05-18 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0006_bodyparts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyparts',
            name='symptom_groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='disease.symptomsgroup'),
        ),
    ]
