# Generated by Django 4.2.1 on 2023-05-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0007_alter_bodyparts_symptom_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodyparts',
            name='symptom_groups',
        ),
        migrations.AddField(
            model_name='bodyparts',
            name='symptom_groups',
            field=models.ManyToManyField(to='disease.symptomsgroup'),
        ),
    ]
