# Generated by Django 4.2.1 on 2023-05-20 23:14

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_birth_alter_user_gender_delete_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=members.models.user_avatar_path),
        ),
    ]
